### ISSUE TITLE
What version does this module support?

### ISSUE THREAD

**Issue by mike442144** [bnoordhuis/node-heapdump#103]
I have require the module in my program, and node version is 6.9.1, But it was strange that when my program crashed, the console output was:

```
 8388190 ms: Mark-sweep 848.1 (1434.1) -> 848.1 (1434.1) MB, 1097.9 / 0.5 ms [allocation failure] [scavenge might not succeed].
```
It seems I hit the 1.4G limit, but I saw the RES value in top command was 4.4G, Can anybody explain why? I didn't have a native add-on module.

And I'm really confused about the snapshots I've got.

**Comment by bnoordhuis** [comment]
External memory (memory allocated with malloc() or operator new) doesn't count towards the JS heap size.  If your application uses lots of buffers or typed arrays, most of its memory will be external.

> And I'm really confused about the snapshots I've got.

That's not really the kind of comment I can work with...  confused how?

**Comment by mike442144** [comment]
Thanks, let me explain the snapshot. I have five snapshots:


[![选区_001.png](https://s29.postimg.org/vvrxm582v/001.png)](https://s29.postimg.org/vvrxm582v/001.png)

 - It seems that the snapshot size is sometimes smaller than the previous one. I guess it is because GC
 - The size of snapshot is far from the RES value in top command, as you mentioned, external memory is not included.

Let's see the following comparisons:
The fifth snapshot compared to the fourth one,
[![选区_002.png](https://s12.postimg.org/wzcqkafyl/002.png)](https://s12.postimg.org/wzcqkafyl/002.png)

The fourth one compared to the third,
[![选区_003.png](https://s7.postimg.org/mnh6nt8e3/003.png)](https://s7.postimg.org/mnh6nt8e3/003.png)

What I'm confused about is why when I compare the fifth to the first, it seems only +60M size delta, but the snapshot file size has +300M, and it is the same with comparing the fourth with the first, size delta is -40M but the file size is 150M bigger than the first.

Let's ignore the external memory and focus on the heap size. Say the program crashed, the heap size was over 1.4G despite the 4.4G total memory usage in top command. What can I do to figure out the memory which cannot be collected because I couldn't find obvious memory leak.

**Comment by bnoordhuis** [comment]
> It seems that the snapshot size is sometimes smaller than the previous one. I guess it is because GC

heapdump collects all garbage before writing out the snapshot so that's not it.

There is no hard 1-to-1 correspondence between heap size and snapshot size.  Some heap layouts generate bigger snapshots than others.  Use file size as a quick gauge but don't read too much into it.

> What can I do to figure out the memory which cannot be collected because I couldn't find obvious memory leak.

That depends on the application.  With for example a game it's simple: write snapshots at the start of the render loop and check in the comparison view if everything gets cleaned up at the next frame.

For server applications there is no silver bullet: many objects and objects varying lifetimes means you may have to look at a lot of snapshots to find what you are looking for.

Example: if your application runs out of memory after 24 hours, take a snapshot every hour and compare them.  Also consider that your application may not have a memory leak but simply gets overpowered by the number of connections after some time.

**Comment by mike442144** [comment]
Thanks, actually my program is a client application rely on `request`, say I have 3 million tasks and divide them into 70 thousand per batch then do one batch after another. In this case, my memory should have been stable, however, it was been always increasing until crash.
