### ISSUE TITLE
Memory leaked when taking a snapshot

### ISSUE THREAD

**Issue by anandsuresh** [bnoordhuis/node-heapdump#90]
I'm noticing this behavior on SmartOS running node v4.5.0 where taking a heap snapshot by sending SIGUSR2 to the process returns a full heap dump, but the process RSS spikes and never drops.

Connecting to the node process using the REPL reveals:

```
> process.memoryUsage()
{ rss: 2252591104, heapTotal: 315919728, heapUsed: 191588688 }
```

Taking successive snapshots only raises the RSS. It seems that the call to delete the snapshot (https://github.com/bnoordhuis/node-heapdump/blob/master/src/heapdump.cc#L128) isn't really reclaiming the memory.

**Comment by bnoordhuis** [comment]
> It seems that the call to delete the snapshot isn't really reclaiming the memory.

That would make it a V8 bug but I don't think it is because it works okay on other platforms.

I'd look into your platform's memory allocator.  Memory fragmentation on smartos tends to be significantly worse compared to other platforms.  The symptoms you describe (RSS going up, never going down) fits that pattern.

There is an alternative allocator (libumem) that may or may not work better, you could try that.  I'll close the issue but feel free to ask follow-up questions.

**Comment by anandsuresh** [comment]
We are already using libumem on all of our node processes. Just wanted to see if you had seen issues like this on other platforms. Will keep digging into it. Thanks.
